[mypy]
python_version = 3.11
ignore_missing_imports = True
follow_imports = skip
warn_return_any = True
warn_unused_configs = True
warn_redundant_casts = True
warn_unused_ignores = True
warn_unreachable = True
disallow_untyped_defs = True
check_untyped_defs = True
no_implicit_optional = True
disable_error_code = import-untyped,no-redef,arg-type

[mypy-app.ui.pages]
disallow_any_generics = False

[mypy-app.api.routes_risk]
disallow_any_generics = False

[mypy-app.ui.data_client]
disallow_any_generics = False
